<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LisoP2P.Core\LisoP2P.Core.csproj" />
    <ProjectReference Include="..\LisoP2P.Net\LisoP2P.Net.csproj" />
    <ProjectReference Include="..\LisoP2P.Media\LisoP2P.Media.csproj" />
    <ProjectReference Include="..\LisoP2P.Storage\LisoP2P.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
