<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LisoP2P.Core\LisoP2P.Core.csproj" />
    <ProjectReference Include="..\LisoP2P.Media\LisoP2P.Media.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LisoP2P.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
